Connecting chats
reliablepsd/clienthub pull request #37
Opened 2021-08-13 12:08 UTC by emalsidog

2021-08-13 12:37 UTC, bubuzavrik requested changes
About your questions:
1. We don't need roomId and subject in url, adding it was my fault. Same redirect to null was invalid realisation cause i think that subjects will be static, but then i find that we will have chat settings, where we can change folders. I've already removed that on master. 

2. You done right with the splitting header. But it would be better if you create wrapper, that will show header for us and show chat or list depending on id of conversation that stored in conversations.room.id

3. As you said currently opened room - in redux: conversations.room.

4. About stretching messages container : 
You can use:
- height in vh {
height: 80vh;
overflow: auto
}
or 
-position fixed:
{
    height: 500px;
    overflow: auto;
    position: fixed;
    bottom: 0;
}
I think that first variant will be better.
Also can you add scrollbar styling, i think it will be much prettier.

Don't forget to pull from master at first.

2021-08-13 12:42 UTC, emalsidog commented
> About your questions:
> 
> 1. We don't need roomId and subject in url, adding it was my fault. Same redirect to null was invalid realisation cause i think that subjects will be static, but then i find that we will have chat settings, where we can change folders. I've already removed that on master.
> 2. You done right with the splitting header. But it would be better if you create wrapper, that will show header for us and show chat or list depending on id of conversation that stored in conversations.room.id
> 3. As you said currently opened room - in redux: conversations.room.
> 4. About stretching messages container :
>    You can use:
> 
> * height in vh {
>   height: 80vh;
>   overflow: auto
>   }
>   or
> * position fixed:
>   {
>   height: 500px;
>   overflow: auto;
>   position: fixed;
>   bottom: 0;
>   }
>   I think that first variant will be better.
>   Also can you add scrollbar styling, i think it will be much prettier.
> 
> Don't forget to pull from master at first.

I have conflicts when pulling from master

2021-08-13 13:04 UTC, bubuzavrik commented
> > About your questions:
> > 
> > 1. We don't need roomId and subject in url, adding it was my fault. Same redirect to null was invalid realisation cause i think that subjects will be static, but then i find that we will have chat settings, where we can change folders. I've already removed that on master.
> > 2. You done right with the splitting header. But it would be better if you create wrapper, that will show header for us and show chat or list depending on id of conversation that stored in conversations.room.id
> > 3. As you said currently opened room - in redux: conversations.room.
> > 4. About stretching messages container :
> >    You can use:
> > 
> > 
> > * height in vh {
> >   height: 80vh;
> >   overflow: auto
> >   }
> >   or
> > * position fixed:
> >   {
> >   height: 500px;
> >   overflow: auto;
> >   position: fixed;
> >   bottom: 0;
> >   }
> >   I think that first variant will be better.
> >   Also can you add scrollbar styling, i think it will be much prettier.
> > 
> > Don't forget to pull from master at first.
> 
> I have conflicts when pulling from master

Conflicts resolved, try to pull it

2021-08-13 13:06 UTC, emalsidog commented
> > > About your questions:
> > > 
> > > 1. We don't need roomId and subject in url, adding it was my fault. Same redirect to null was invalid realisation cause i think that subjects will be static, but then i find that we will have chat settings, where we can change folders. I've already removed that on master.
> > > 2. You done right with the splitting header. But it would be better if you create wrapper, that will show header for us and show chat or list depending on id of conversation that stored in conversations.room.id
> > > 3. As you said currently opened room - in redux: conversations.room.
> > > 4. About stretching messages container :
> > >    You can use:
> > > 
> > > 
> > > * height in vh {
> > >   height: 80vh;
> > >   overflow: auto
> > >   }
> > >   or
> > > * position fixed:
> > >   {
> > >   height: 500px;
> > >   overflow: auto;
> > >   position: fixed;
> > >   bottom: 0;
> > >   }
> > >   I think that first variant will be better.
> > >   Also can you add scrollbar styling, i think it will be much prettier.
> > > 
> > > Don't forget to pull from master at first.
> > 
> > 
> > I have conflicts when pulling from master
> 
> Conflicts resolved, try to pull it

It worked :)

2021-08-16 07:39 UTC, bubuzavrik requested changes

2021-08-16 07:39 UTC, bubuzavrik commented on client/src/components/Messages/ConversationsWrapper/index.js
> +      {Object.keys(room).length > 0 ? <Thread /> : <ConversationsList />}
Object.keys(room).length always more than 0, cause room it's object that have some keys, you can see all of them in reducer. So Thread will be rendered always.

2021-08-16 07:39 UTC, bubuzavrik commented on client/src/components/Messages/Thread/index.js
> +import { NoData } from "../../UI/NoData";
28 string it's not styles

2021-08-16 07:39 UTC, bubuzavrik commented on client/src/components/Messages/Thread/index.js
> +  const settingsMenu = [
This array can be mapped. It will make code size lesser

2021-08-16 07:39 UTC, bubuzavrik commented on client/src/redux/reducers/conversation.js
> +  CHOOSE_CONVERSATION_ROOM,//Same
Remove one of the sames

2021-08-16 07:51 UTC, emalsidog commented on client/src/components/Messages/ConversationsWrapper/index.js
> +      {Object.keys(room).length > 0 ? <Thread /> : <ConversationsList />}
I have tried to log it in the console and it was empty. Even with default values in the reducer

2021-08-16 08:01 UTC, bubuzavrik commented on client/src/components/Messages/ConversationsWrapper/index.js
> +      {Object.keys(room).length > 0 ? <Thread /> : <ConversationsList />}
![image](https://user-images.githubusercontent.com/22328251/129531213-1a958e55-b744-4263-b14b-2e7040fbccf6.png)

2021-08-16 08:02 UTC, bubuzavrik commented on client/src/components/Messages/ConversationsWrapper/index.js
> +      {Object.keys(room).length > 0 ? <Thread /> : <ConversationsList />}
Screen with default values

2021-08-16 08:04 UTC, bubuzavrik commented on client/src/components/Messages/ConversationsWrapper/index.js
> +      {Object.keys(room).length > 0 ? <Thread /> : <ConversationsList />}
You need to check id, cause chats will use this id for messaging

2021-08-16 08:25 UTC, emalsidog commented on client/src/components/Messages/ConversationsWrapper/index.js
> +      {Object.keys(room).length > 0 ? <Thread /> : <ConversationsList />}
Ok, get it

2021-08-16 08:36 UTC, emalsidog commented
Fixed your remarks

2021-08-16 08:37 UTC, bubuzavrik requested changes

2021-08-16 08:37 UTC, bubuzavrik commented on client/src/components/Messages/Thread/index.js
> +        <MenuItem onClick={handleSettings} key="notes">
Use map

2021-08-16 08:40 UTC, bubuzavrik commented
![image](https://user-images.githubusercontent.com/22328251/129535945-0f201340-7c04-4d3d-b5f3-5191aacff244.png)

In the assigned column should be names instead of ids

2021-08-16 08:49 UTC, emalsidog commented on client/src/components/Messages/Thread/index.js
> +        <MenuItem onClick={handleSettings} key="notes">
Do you mean to create a 4 element array and for each key return a MenuItem? Or you mean just map a settingsMenu?

2021-08-16 08:52 UTC, emalsidog commented
> ![image](https://user-images.githubusercontent.com/22328251/129535945-0f201340-7c04-4d3d-b5f3-5191aacff244.png)
> 
> In the assigned column should be names instead of ids

Should i use a request to get user by id? For each row?

2021-08-16 08:53 UTC, bubuzavrik commented
> > ![image](https://user-images.githubusercontent.com/22328251/129535945-0f201340-7c04-4d3d-b5f3-5191aacff244.png)
> > In the assigned column should be names instead of ids
> 
> Should i use a request to get user by id? For each row?

You already have this info. Conversation can be assigned only to members, and you already have members array

2021-08-16 09:16 UTC, emalsidog commented
Fixed issue with the table but i am not sure, that map is a good idea because I have put different icons and i can not just create array with 4 element and map the same MenuItem

2021-08-16 09:19 UTC, bubuzavrik requested changes

2021-08-16 09:19 UTC, bubuzavrik commented on client/src/components/Messages/Thread/index.js
> +
You can create array of {key:'', icon:()=>Icon, name:'' }, and map it

2021-08-16 09:26 UTC, emalsidog commented
Hope its ok :)

2021-08-16 09:41 UTC, bubuzavrik approved these changes

2021-08-16 09:41 UTC, merged