Added "Edit someone's info" page
reliablepsd/clienthub pull request #42
Opened 2021-08-17 13:02 UTC by emalsidog

### Fixed:

1. Minor UI bugs

### Added:

1. Edit someone's profile page
2. Danger and default types to button
3. Possibility to redirect after deleting user

2021-08-17 13:46 UTC, bubuzavrik requested changes

2021-08-17 13:46 UTC, bubuzavrik commented on client/src/components/CompanyOwner/index.js
> +      <Route exact path={`${match.path}/manage/:id`} component={UpdateCompanyTeamMember} />
This route should be inside ManageTeamMembers

2021-08-17 13:46 UTC, bubuzavrik commented on client/src/components/Messages/ConversationsWrapper/index.js
> +          <Redirect to={`${match.path}/list/all`} />
we don't need list here, cause ing Messages/index.js we have route which renders this component, and this is roution inside component

2021-08-17 13:46 UTC, bubuzavrik commented on client/src/components/Profile/UpdateCompanyTeamMember/index.js
> +  }, [dispatch, params]);
useEffect cannot control objects and arrays, cause it can't make deep comparsion, so you should use params.id instead of params

2021-08-17 13:46 UTC, bubuzavrik commented on client/src/components/Profile/UpdateCompanyTeamMember/index.js
> +      companyRole: displayedUser.role || 3,
you can rename companyRole to role and  use {...displayedUser}. also why initial role by default = 3?

2021-08-18 07:17 UTC, bubuzavrik requested changes

2021-08-18 07:17 UTC, bubuzavrik commented on client/src/components/Profile/UpdateCompanyTeamMember/index.js
> +
Form fields handlers already exists in src/utils/formikHelpers, you need only to import them.

2021-08-20 07:11 UTC, bubuzavrik requested changes
Check all files, use aliases instead of default imports if it's component or reusable. 
If this is component for another component (client/src/Messages/Thread/Message) you can import it without aliases.

2021-08-20 07:11 UTC, bubuzavrik commented on client/src/components/ManageClient/UpdateClientTeamMember/DemoteToClientTeam/Step1/index.js
> +
check client/craco.config.js. Use aliases instead of default imports with ../../../.
also if you create new component, add it to client/src/components/index.js

2021-08-20 08:14 UTC, emalsidog commented
I hope its done

2021-08-20 09:16 UTC, bubuzavrik requested changes

2021-08-20 09:16 UTC, bubuzavrik commented on client/src/components/index.js
export { ProjectTeam, SignIn, SignUpOwner, UsersList, ManageClient, ManageTeam} from '@components'

2021-08-20 09:16 UTC, bubuzavrik commented on client/src/components/Profile/UpdatePhoto/index.js
> +
@utils

2021-08-20 09:16 UTC, bubuzavrik commented on client/src/components/UI/Button/index.js
> +
@utils

2021-08-20 09:16 UTC, bubuzavrik commented on client/src/components/UI/Select/index.js
>        backgroundColor: '#fff',
theme.palette.white.highemphasis

2021-08-20 09:51 UTC, emalsidog commented on client/src/components/index.js
Its not working is such a way. I do not know why

2021-08-20 10:11 UTC, emalsidog commented on client/src/components/UI/Select/index.js
>        backgroundColor: '#fff',
I cant get mui theme object inside component

2021-08-20 10:11 UTC, bubuzavrik commented on client/src/components/index.js
okay, i'll check after merge

2021-08-20 10:21 UTC, merged