Lots of things
reliablepsd/clienthub pull request #56
Opened 2021-08-27 12:07 UTC by emalsidog

I have only one question about this part

![image](https://user-images.githubusercontent.com/67701732/131125027-b8913bd9-d16f-466f-b326-f2203b3238cf.png)

I have temporarily commented your code to demonstrate that formatted messages are working. But i think we need different types for messages. To add html type, if it has html tags. Also I thing we need to fix sever response when getting messages. They have different structure and unnecessary fields (When getting searched results)

2021-08-30 07:19 UTC, bubuzavrik requested changes

2021-08-30 07:19 UTC, bubuzavrik commented on client/src/translates/ru.js
> +  Filter: 'Фильтер',
Фильтр

2021-08-30 07:19 UTC, bubuzavrik commented on client/src/translates/ru.js
> +  'Add People': 'Добавить Людей',
98 and 99 rows same, better to use `${translateText('Add People')} +` in code and "+" you can add if needed

2021-08-30 07:19 UTC, bubuzavrik commented on client/src/translates/ru.js
> +  'Not assigned': 'Не поручено',
108 and 118 row, already exists. debug:true also said about same translation keys

2021-08-30 07:34 UTC, emalsidog commented on client/src/translates/ru.js
> +  'Not assigned': 'Не поручено',
Hey, I have a question about deleting user. Can we delete SuperAdmin from chat or not? I have deleted him from the chat but server still gives me info about chats where user does not exist

2021-08-31 06:48 UTC, bubuzavrik requested changes

2021-08-31 06:48 UTC, bubuzavrik commented on client/src/components/Messages/Thread/index.js
> +            onChange={(event, editor) => {
don't create callbacks in render

2021-08-31 11:49 UTC, merged