Updated theme logic
reliablepsd/clienthub pull request #85
Opened 2021-09-14 13:00 UTC by emalsidog

I am sorry. There are some changes I made yesterday in the Thread component. I have not know that you started working on Front end too. I have removed my today's changes.

About themes. I have left old theme object structure in compatibility purposes but I have also created a new one based on names that I have seen on Figma. Also, I have decided to use redux to store current theme because <ThemeSwitcher /> can be called anywhere and useTheme hook will not update theme object in the Theme component. 

Again, I apologize for my yesterday's changes.

2021-09-14 13:16 UTC, bubuzavrik commented on client/src/components/Projects/Thread/index.js
>          </MenuItem>
You want split this component on some lesser components, cause here too much rows and it's very hard to debug

2021-09-14 13:17 UTC, bubuzavrik requested changes
Try to make components 200 rows and lesser, cause if there are 700+, it's very hard to debug

2021-09-14 13:18 UTC, emalsidog commented
> Try to make components 200 rows and lesser, cause if there are 700+, it's very hard to debug

Should I make a pull?

2021-09-14 14:48 UTC, bubuzavrik commented
> > Try to make components 200 rows and lesser, cause if there are 700+, it's very hard to debug
> 
> Should I make a pull?

Yes

2021-09-15 13:26 UTC, bubuzavrik approved these changes

2021-09-15 13:26 UTC, merged