Working on 'All users' page
reliablepsd/clienthub pull request #9
Opened 2021-07-29 10:54 UTC by emalsidog

Hey, need your help. I do not know how to make the table univarsal (Make it work with any rows). So its now 'hardcoded'. And i am not sure if we need this to be universal. Also, I have problems with popum menu inside subrow. It opens parent menu. Hope, you will help me :)

2021-07-29 11:55 UTC, bubuzavrik reviewed
> Hey, need your help. I do not know how to make the table univarsal (Make it work with any rows). So its now 'hardcoded'. And i am not sure if we need this to be universal. Also, I have problems with popup menu inside subrow. It opens parent menu. Hope, you will help me :)

1. You can use something like this for making the table universal Object.keys(data).map((key)=>data[key]) . But in this way you may have problems if your table will have not only text info, for example images or fields.

2. About popup: your row contains PopupMenu components, but subrow - not, so when you clicks on button in subrow, you open parent's popup. You can use your DataTableRow component recursively to avoid this

2021-07-29 11:55 UTC, bubuzavrik commented on client/src/components/Home/index.js
>  ];
Here path should be named as group of pages that will contains actions (for example manage, add...). Actions will have own routes inside this components

2021-07-29 11:55 UTC, bubuzavrik commented on client/src/components/ManageTeamMembers/fields.js
> +  {
I think, that headerCells can be array of strings, not of objects

2021-07-29 11:55 UTC, bubuzavrik commented on client/src/components/UI/Table/index.js
> +};
Why same components exists in UI/Table/DataTableRow/index.js?

Also one file = one component

2021-07-30 09:29 UTC, bubuzavrik requested changes

2021-07-30 09:29 UTC, bubuzavrik commented on client/src/components/UI/Pagination/index.js
> +const range = (from, to, step = 1) => {
Move to helpers.js

2021-07-30 09:29 UTC, bubuzavrik commented on client/src/components/UI/Table/DataTableRow/index.js
> +  const [isActionMenuVisible, setIsActionMenuVisible] = useState();
Add default value to useState(). It shouldn't be undefined

2021-07-30 09:29 UTC, bubuzavrik commented on client/src/components/UI/Table/DisplayRowActions/index.js
> +      </button>
Here you can use Button component from UI folder. You just need ti restyle it

2021-07-30 11:59 UTC, bubuzavrik commented on client/src/components/UI/Button/index.js
> +    <ButtonBase onClick={onClick} disabled={disabled} className={classes.button} type={type}>
components -> UI -> Button

2021-07-30 12:06 UTC, emalsidog commented on client/src/components/UI/Button/index.js
> +    <ButtonBase onClick={onClick} disabled={disabled} className={classes.button} type={type}>
I don't get it. I have added onClick to ButtonBase, because it was in props of Button but it wasnt used

2021-08-02 11:36 UTC, bubuzavrik commented on client/src/redux/sagas/user.js
> +      axios.post("/users/check-signup-token", { token })
Instead of axios, use axios instance from src/services/api

2021-08-02 14:53 UTC, bubuzavrik commented on client/src/components/UI/PopupMenu/styles.js
> +    background: "#FFFFFF",
Use colors from theme instead of directly

2021-08-03 09:16 UTC, bubuzavrik approved these changes

2021-08-03 09:21 UTC, merged